// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbtcuxqergxanwgxnpmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidGN1eHFlcmd4YW53Z3hucG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MTgzMTEsImV4cCI6MjA1MzE5NDMxMX0.loBPdFSxLN6CqaIkNumNn0yG-3KkPBc6c4FovT5dE_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);